# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:
- stage: __default
  jobs:
  - job: build_hello
    pool:
      name: Pool-Brok
    steps:
    - task: PowerShell@2
      displayName: apply on openshift
      inputs:
        targetType: inline
        script: >
          oc login --token=sha256~RUzo7Cifn_vduECsENmPKM1AcB9UX-CxzbgRvfLj9Fw --server=https://api.stgocp.efg-hermes.local:6443

          oc project core

    - task: PowerShell@2
      displayName: Deploying to openshift
      inputs:
        targetType: inline
        script: >
          oc apply -f SampleApiToDeployOnOpenShift/oc-yamls/hello-deployment.yaml

          oc apply -f SampleApiToDeployOnOpenShift/oc-yamls/hello-route.yaml

          oc rollout restart deployment/hello-deployment